### ISSUE TITLE
What can we put in boxes?

### ISSUE THREAD

**Issue by mheiber** [tc39/proposal-symbols-as-weakmap-keys#3]
Are all of the following OK?

```js
Box(Box(Box({})));
Box(true);
Box(Symbol());
```

**Comment by ljharb** [comment]
If this is called "box" then it has nothing to do with weak semantics; I would assume *any* value, including another Box, could be stored in a box.

**Comment by littledan** [comment]
I don't really understand the point of putting a Box around a primitive. Why not just use the primitive? At the same time, I don't see the harm that it would cause to add this feature.

**Comment by jridgewell** [comment]
> I don't really understand the point of putting a Box around a primitive. Why not just use the primitive?

I can see two uses:

1. Boxing anything that's user-provided (user being the user of a function)
2. Simple template equality with out-of-band data

## 1. Boxing anything that's user-provided

Imagine:

```js
function foo(data) {
  return #{
    id: 0,
    data: box(data)
  };
}
```

Here, `data` is user-provided data. To differentiate it from the real contents of the record, it's placed in a box. I know that `record.id` comes from inside the record because it's not boxed. (This is provided that nothing "inside the record" itself has to be boxed)

## 2. Simple template equality with out-of-band data

Imagine:

```js
function template(data) {
  return #{ 
    type: 'div',
    textContent: box(data),
  };
}
```

Templates have static structure, which can be represented as a record pretty easily. When I render a template the first time, it has to render everything into DOM. When I re-render (using the exact same template), I only want to render the parts that have changed.

The easiest way to accomplish re-rendering it to store data out-of-band. This would allow me to use simple `===` equality checks to see if I'm reusing the same template. This leads me to storing user-provided data outside the record (ie, not doing `textContent: box(data)` directly):

```js
function template(data) {
  return {
    structure: #{
      type: 'div',
      textContent: box(SOMETHING),
    },
    outOfBandData: [
      data,
    ],
  };
}
```

I can now do `renderable.structure === alreadyRendered.structure` to see if I'm re-rendering the same template.

But what do I use for `SOMETHING`? With the current restriction, it has to be an object. And to ensure the `structure === structure` check works correctly, it has to be the **same** object every single time. So now I need to store N objects along with the `template` function that will be used as my box values for each `template` call.

```js
const HOLES = [
  Object.freeze(Object.create(null)),
  // … how ever many hole objects I need
];

function template(data) {
  return {
    structure: #{
      type: 'div',
      textContent: box(HOLES[0]),
    },
    outOfBandData: [
      data,
    ],
  };
}
```

It'd be easier if we could just use a primitive here. Now I can update it to just `textContent: box(0)`, and not worry about storing the objects at all.

```js
function template(data) {
  return {
    structure: #{
      type: 'div',
      textContent: box(0),
    },
    outOfBandData: [
      data,
    ],
  };
}
```

**Comment by ljharb** [comment]
What's the point of a generic container if it can't contain generically?

**Comment by littledan** [comment]
(I remain baffled by the discussion of WeakRefs here; WeakRefs have as much to do with Box as they each do to single-element Arrays; if you think they're redundant, it must be that we're not explaining what each of them do very clearly. "generic container" describes neither Box nor WeakRef.)

This proposal has moved towards Symbols as WeakMap keys, so I'm closing this issue.
